services:
  mysql:
    image: mariadb:11.4.2
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.8.1}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-23-11-8-1}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - ./slurm.conf:/etc/slurm/slurm.conf
      - ./cgroup.conf:/etc/slurm/cgroup.conf
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.8.1}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - ./slurm.conf:/etc/slurm/slurm.conf
      - ./cgroup.conf:/etc/slurm/cgroup.conf
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  c1:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.8.1}
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - ./slurm.conf:/etc/slurm/slurm.conf
      - ./cgroup.conf:/etc/slurm/cgroup.conf
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.8.1}
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf
      - ./slurm.conf:/etc/slurm/slurm.conf
      - ./cgroup.conf:/etc/slurm/cgroup.conf
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
